
INSERT INTO products (
  mongo_id,
  name,
  brand,
  category,
  short_description,
  full_description,
  usage_text,
  image_url,
  images,
  status,
  industries,
  surfaces,
  features,
  created_at,
  updated_at
)
VALUES
(
        '6a170764c312f5c068fac72e',
        'Deer™ Wood Contact Adhesive',
        'Deer™ Brand',
        'Industrial',
        'High-strength contact adhesive for wood and laminates bonding.',
        'Deer™ Wood Contact Adhesive is a solvent-based neoprene contact adhesive formulated for bonding wood, laminates, and veneers. It forms an instant, durable bond on contact and is widely used in furniture manufacturing and interior fit-outs.',
        'Apply evenly to both surfaces. Allow to dry for 5–10 minutes until tacky. Press surfaces firmly together. Full bond strength achieved within 24 hours.',
        'images/products/deer-wood-contact.jpg',
        '[]',
        'Available',
        '["Carpentry","Flooring"]',
        '["Wood","Laminates"]',
        '["Instant contact bond","High solids content","Excellent heat resistance","Suitable for vertical surfaces"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac72f',
        'Deer™ Neoprene Rubber Adhesive',
        'Deer™ Brand',
        'Industrial',
        'Flexible neoprene adhesive for rubber, leather, and foam bonding.',
        'Deer™ Neoprene Rubber Adhesive provides a strong, flexible bond for rubber, leather, and foam materials. Ideal for automotive interiors, upholstery work, and soft furnishings requiring a pliable yet durable bond.',
        'Clean surfaces thoroughly. Apply to both surfaces and allow to flash off for 5 minutes. Press together firmly.',
        'images/products/deer-neoprene.jpg',
        '[]',
        'Available',
        '["Automotive","Upholstery"]',
        '["Rubber","Leather","Foam & Sponge"]',
        '["Flexible bond","Resistant to vibration","Good chemical resistance","Suitable for curved surfaces"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac730',
        'Horsemen™ Industrial Spray Adhesive',
        'Horsemen™ Brand',
        'Industrial',
        'Fast-tack spray adhesive for packaging, labels, and foam.',
        'Horsemen™ Industrial Spray Adhesive delivers a consistent, wide-coverage bond ideal for packaging lines, label application, and foam bonding. Its spray format allows fast, even application across large surface areas.',
        'Shake can well. Hold 20–30 cm from surface and spray evenly. Bond immediately or allow to dry for repositionable tack.',
        'images/products/horsemen-spray.jpg',
        '[]',
        'Available',
        '["Packaging","Fashion"]',
        '["Paper","Labels","Foam & Sponge"]',
        '["360° spray valve","Repositionable or permanent bond","Fast tack","Low VOC formulation"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac731',
        'Horsemen™ Waterproof Tile Adhesive',
        'Horsemen™ Brand',
        'Industrial',
        'Waterproof adhesive for tiles, stone, and ceramic surfaces.',
        'Horsemen™ Waterproof Tile Adhesive is a polymer-modified adhesive designed for fixing tiles, stone, and ceramics in wet areas including bathrooms, kitchens, and pools. Provides excellent water and mould resistance.',
        'Mix with water to paste consistency. Apply with notched trowel. Press tiles firmly and allow 24 hours before grouting.',
        'images/products/horsemen-tile.jpg',
        '[]',
        'Available',
        '["Plumbing & Sanitary","Waterproof"]',
        '["Tiles","Stone Ceramics","Metal"]',
        '["Waterproof formula","Mould resistant","Suitable for wet areas","Non-slump on vertical surfaces"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac732',
        'Premier™ High Temperature Adhesive',
        'Premier™ Brand',
        'Industrial',
        'Heat-resistant adhesive for automotive and insulation applications.',
        'Premier™ High Temperature Adhesive is engineered to maintain bond strength at elevated temperatures up to 200°C. Ideal for automotive engine bays, exhaust insulation, and industrial heat-shielding applications.',
        'Apply to clean, dry surfaces. Allow 15 minutes open time. Cure under heat or at room temperature over 48 hours.',
        'images/products/premier-high-temp.jpg',
        '[]',
        'Available',
        '["Automotive","Insulation"]',
        '["Metal","Fibreglass Wool"]',
        '["Rated to 200°C","Chemical resistant","Non-corrosive","Paintable after cure"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac733',
        'Premier™ Carpet & Turf Adhesive',
        'Premier™ Brand',
        'Industrial',
        'Strong floor adhesive for carpet and artificial turf installation.',
        'Premier™ Carpet & Turf Adhesive is a high-tack, water-resistant adhesive for securing carpets and artificial turf to concrete, timber, and screed subfloors. Designed for commercial and residential flooring projects.',
        'Apply to subfloor using a notched trowel. Lay carpet or turf within 20 minutes. Roll firmly with a 50 kg roller.',
        'images/products/premier-carpet.jpg',
        '[]',
        'Available',
        '["Flooring"]',
        '["Carpet","Turf"]',
        '["High initial tack","Water resistant","Low odour","Compatible with underfloor heating"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac734',
        'Premier™ Wallpaper Paste',
        'Premier™ Brand',
        'Commercial',
        'Ready-mix paste for wallpaper and wall covering installation.',
        'Premier™ Wallpaper Paste is a smooth, non-staining adhesive suitable for all standard wallpapers and wall coverings including vinyl, fabric, and textured papers. Easy to apply and clean up.',
        'Apply paste to back of wallpaper using a brush. Allow paper to soak for 3–5 minutes before hanging.',
        'images/products/premier-wallpaper.jpg',
        '[]',
        'Available',
        '["Fashion"]',
        '["Wallpaper"]',
        '["Ready to use","Non-staining","Suitable for all wallpaper types","Easy water clean-up"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac735',
        'Rhino™ Heavy Duty Metal Adhesive',
        'Rhino™ Brand',
        'Industrial',
        'Industrial-strength adhesive for metal, plastic, and composite bonding.',
        'Rhino™ Heavy Duty Metal Adhesive is a two-part epoxy system providing structural bond strength for metals, plastics, and composites. Used extensively in marine fabrication, lift and escalator maintenance, and heavy engineering.',
        'Mix Part A and Part B in equal ratio. Apply to clean degreased surfaces. Clamp for 30 minutes. Full cure in 24 hours.',
        'images/products/rhino-metal.jpg',
        '[]',
        'Available',
        '["Marine","Lift & Escalator"]',
        '["Metal","Plastics & Acrylics"]',
        '["Two-part epoxy","Structural bond strength","Saltwater resistant","Gap filling capability"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac736',
        'Rhino™ Marine Sealant',
        'Rhino™ Brand',
        'Industrial',
        'Flexible marine-grade sealant for below and above waterline use.',
        'Rhino™ Marine Sealant is a polyurethane-based sealant designed for the marine environment. It bonds and seals metal, rubber, and plastic fittings both above and below the waterline. Resists fuel, oil, and saltwater.',
        'Clean surfaces with solvent. Apply sealant with caulking gun. Tool to smooth finish within 15 minutes. Cure: 48 hours.',
        'images/products/rhino-marine.jpg',
        '[]',
        'Available',
        '["Marine","Waterproof"]',
        '["Metal","Rubber"]',
        '["Above and below waterline","Fuel and oil resistant","Permanently flexible","Paintable after cure"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac737',
        'Deer™ Laminate Contact Adhesive',
        'Deer™ Brand',
        'Industrial',
        'Premium contact adhesive for high-pressure laminates and veneers.',
        'Deer™ Laminate Contact Adhesive is a high-solids neoprene contact adhesive specifically formulated for bonding high-pressure laminates (HPL) to substrates including MDF, plywood, and particleboard. Provides a flat, bubble-free bond.',
        'Apply to both surfaces with a roller or brush. Allow 10 minutes dry time. Align carefully and press from centre outward to eliminate air pockets.',
        'images/products/deer-laminate.jpg',
        '[]',
        'Available',
        '["Carpentry"]',
        '["Laminates","Wood"]',
        '["High solids content","Bubble-free bond","Suitable for post-forming","Fast setting"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac738',
        'Horsemen™ Foam Bond Adhesive',
        'Horsemen™ Brand',
        'Industrial',
        'Specialist adhesive for bonding foam, sponge, and upholstery materials.',
        'Horsemen™ Foam Bond Adhesive is a solvent-based contact adhesive designed for bonding foam, sponge, and polyurethane materials used in upholstery, mattresses, and cushioning products. Maintains flexibility after cure.',
        'Apply to both foam surfaces. Allow 5 minutes open time. Press surfaces together. Bond achieves full strength after 1 hour.',
        'images/products/horsemen-foam.jpg',
        '[]',
        'Available',
        '["Upholstery","Packaging"]',
        '["Foam & Sponge","Leather"]',
        '["Remains flexible","No foam attack","High coverage rate","Suitable for all foam densities"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      ),
(
        '6a170764c312f5c068fac739',
        'Rhino™ Cooling Tower Adhesive',
        'Rhino™ Brand',
        'Industrial',
        'High-performance adhesive for cooling tower and HVAC insulation.',
        'Rhino™ Cooling Tower Adhesive is formulated for bonding fibreglass wool, rock wool, and metal components in cooling towers and HVAC systems. Resistant to constant moisture, heat cycling, and chemical exposure.',
        'Apply to cleaned metal surface. Press fibreglass wool firmly. Allow 2 hours before exposure to water. Full cure: 72 hours.',
        'images/products/rhino-cooling.jpg',
        '[]',
        'Available',
        '["Cooling Process","Insulation"]',
        '["Fibreglass Wool","Metal"]',
        '["Moisture resistant","Withstands heat cycling","Non-corrosive to metal","High peel strength"]',
        '2026-05-27 15:01:56',
        '2026-05-27 15:01:56'
      );
